### ISSUE TITLE
gitlab での osgeo-jp グループの作成

### ISSUE THREAD

**Issue by hfu** [OSGeo-jp/asia2018#8]
OSGeo.JP 国連ベクトルタイルツールキットワークショップの準備を進めていたところ、ハンズオンで使うソースデータのサイズが概ね次の通りであることが分かってきました。

- OpenStreetMap 6-46-30 モジュール(gzip 圧縮) 106MB
- 地球地図スリランカ(gzip 圧縮) 6.4MB

これらのデータをレポジトリから共有しておきたいのですが、GitHub だとファイルサイズのハードリミットが 100MB です。他方、GitLab では、もう少し大きなファイルを扱ってくれます。

https://gitlab.com/hfujimura からホストしても良いのですが、アカウント名が長くて、打ってもらうのが辛そうです。

ということで、https://gitlab.com/osgeo-jp/ を作ってみたいです。

**Comment by wata909** [comment]
よろしいかと思います！

**Comment by hfu** [comment]
空のグループアカウントを作りました。
https://gitlab.com/osgeo-jp

次の趣旨で運営委員会 ML におはかりすることにします。

- （本イシューに書いた事情で）gitlab に osgeo-jp グループを作りたい。
- ついては、作った。コメントなどあれば頂ければ幸い。
- 特段の議論をすべきところがなければ、ハンズオンのデータを上げていく。
- グループへ参加したいなどのコメントもあれば頂ければ幸い。なお、ハンズオンのレポジトリを作成する際に、ask me anything (ama) レポジトリをつくり、その中でグループへの参加については、当面、イシューに書いてもらえれば藤村（hfujimura）が処理をする旨書くつもり。

**Comment by hfu** [comment]
https://gitlab.com/osgeo-jp を作成し、運営委員会 ML にお諮りしました。
今後、運営委員会でのコメントに添いつつ、作業を進めていきたいと思います。
