### ISSUE TITLE
ハンズオンの事前準備事項を満たしていない参加者への全般対処方針

### ISSUE THREAD

**Issue by hfu** [OSGeo-jp/asia2018#9]
# 問題の記述
ハンズオンの事前準備事項には、次のように書いてある。
>Participants shall install Node.js, tippecanoe, and git in their computing environment.

しかし、現実問題として参加者はほとんどインストールできてないことを想定したほうがよい。

どう対処するか。

# 全般対処方針
- ハンズオンの構成は、(1) 一挙手一投足を確認するフェーズ、(2) 自分でカスタマイズしてみるフェーズに分け、なるべく (1) を簡単にする方向で準備を進めている。うち (2) の時間は実習的になるので、(1) での脱落は、その時間を使ってベストエフォートの範囲内で救済を試みる。
- 救済は、(a) 持ち込んでいただいた計算機の上での救済、 (b) ログイン環境への案内による救済、 (c) 救済を断念し、ひきつづき説明を聞いていただくことをお願いする、の三段階とする。現実として、段階 (a) での完璧を期するリソースの余裕はないと想定する。
- 上記 (a) の実施においては、正規の方法ではないハンズオン特有の回避手段を準備する余裕はないと認識している。例えば、ハンズオン環境内部 LAN の敷設は試みるが、USB メモリの使い回しは試みない。具体的な方針は、個別の課題で整理する。

**Comment by picaosgeo** [comment]
受講者リストのピックアップは次の通りです。

- Arjan Odedra　午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。
- Dhadimuni Dimesh Dharmathilake 午前中にGeoServerを受講しているのでスキルは大丈夫そう
- Isuru Biyanwila　SLEUTHを受講している　(?)
- Maulik Bhagat 午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。
- Pillappan Karuppiah　午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。
- PONGSakorn Udombua　QGIS LAStoolを受講している
- Pradeep Lakshan Dissanayala　SLEUTHを受講している　(?)
- R.N.S Rajapaksha　午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。W01とブッキング
- Rahul Kanani　午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。
- SantoshGaikwad　　午前中にZOO-Projectを受講しているので、OSGeoLive環境がある。
- Vichithra Sampath　　SLEUTHを受講している　(?)

**Comment by hfu** [comment]
ありがとうございます。比較的、スキルの高いプロフェッショナルの濃度が高そうで、ありがたいことだと思います。

company の表示を眺めていたところ、ポートオーソリティや都市開発局と、それから http://www.nascentinfo.com さんからのご参加が多いようですね。とてもありがたいことで、研修の内容を、これからできる範囲内で、やや大縮尺寄りにしていこうと思っています。

大縮尺は大縮尺で、とても面白いので、そこにフォーカスしていけると、面白いだろうなあと思っています。

**Comment by yoichigmf** [comment]
もし利用されるならThinkPad230とWifiルータを持参するのでそれをサーバとして利用していただいてもかまいません。UbuntuかなにかをインストールしておいてそこにWifiまたはイーサネットでアクセスしてもらうという環境は作れます

**Comment by hfu** [comment]
@yoichigmf さん、それは、とてもありがたいです！私も古い AirMac Extreme を持っていて確実に横につながることができる LAN を作ろうと思っていましたが、つなげる先が Windows 10+WSL の非力な $200 PC でした。本物の Ubuntu が入ったサーバがあれば、とてもありがたいですし、経験があります。

私が過去に行ったハンズオンでは、user1, user2, user3, user4, user5 をアドホックに作って、自己環境では脱落しかけた人に、そのユーザアカウントを書いた紙を渡してサーバ環境に乗り移ってもらっていました。

**Comment by yoichigmf** [comment]
Ubuntu16/04 がインストールされた環境はありますがそれでいいでしょうか？他のOSがよければ教えてください。あとNECの家庭用のWifiルータを持ち出せるのがあるのでそこにこのサーバをつなげばWifiかイーサネットで接続できる環境は作れます。

**Comment by hfu** [comment]
ありがとうございます。基本的に「Node.js と git と Tippecanoe が動けばどの環境でもいける」という、いかにも Java をこじらせたような考え方を私は持っていまして、Ubuntu 16/04 をご用意いただけるのであれば、それで非常にありがたいと思います。可能であれば、Tippecanoe を導入しておいていただけると、とても安心です。（概ね、Tippecanoe を導入するために、あるいはその他の拡張を導入するために、隠れ要求として、C++ コンパイラが必要であったりします...。）

私個人は、Ubuntu の 16 および 18 と、Redhat のいかにも古いものに、新しい C++ コンパイラをソースから導入したものと、Windows 10 + WSL + Ubuntu と、macOS とで、経験を積んでいるところです。

接続は、基本的にはイーサネットは考えずに Wifi のみを積極的にサポートしていくことにしたいと思っています。（私自身、たぶんイーサネットケーブルは持っていかないので、受講者の方にイーサネットケーブルを希望する方がいらっしゃったら、ベストエフォートでの対応にとどめたいと思っています。）

**Comment by yoichigmf** [comment]
了解しました。マシンとルータ持参します。

**Comment by hfu** [comment]
脱落シナリオは、基本的に次の３つだと思っています。

1. PC を持参されていない、または PC がネットワークに繋がらない。
2. シェルがない、Node.js が動かない。
3. Tippecanoe がコンパイルできない。pietra（のために必要な sqlite3 ）がコンパイルできない。

いずれも、トラブルが起こってしまったら深追いはせずにログイン環境に避難してもらうようにしたいと思っています。

脱落者の対応も検討が必要ですが、他方で、スキルの高い参加者もおられるはずで、そちらのニーズにも対応していく必要があると想定しています。

**Comment by hfu** [comment]
現実には、お一人の方について、事前の環境準備が十分ではない状態でしたが、リモートログイン環境に誘導するよりは、持参された Windows 10 PC に Windows Subsystem for Linux を導入してもらって、少しでも作業を進めてもらうアプローチを取りました。

しかし、いざというときに誘導できるリモートログイン環境があるということは、非常に心強いことでした。
